 const receiveDossierModal = {
     title: "Receive Dossier",
     disclaimer: "Once the colaborator sends you the Dossier SEED you can scan the QRcode or enter the URL. After that you will be prompted to choose a place and a name for the new Dossier",
     orLabel: "or",
     isDossierNameStep: false,
     secretCodeForReceive: {
         readOnly: true,
         // the real code will be generated by the service
         value: "SECRET_CODE_HERE",
     },
     dossierNameInput: {
         label: "Name your new dossier",
         value: "",
     },
     destinationOptionsForDossier: {
         label: "Dossier destination",
         value: "",
         selectOptions: "Wallet root, / | Data, /data | New Dossier, /new-dossier",
     },
     buttons: {
         nextButton: {
             label: "Next",
             eventName: "next-receive-dossier",
             buttonClass: "btn-confirm-secondary",
         },
         finishButton: {
             label: "Finish",
             eventName: "finish-receive-dossier",
             buttonClass: "btn-confirm-secondary",
             disabled: true
         }
     },
     error: {
         hasError: false,
         errorMessage: "",
         errorLabels: {
             fileExistsLabel: "A file with the same name already exists!",
             nameNotEmptyLabel: "The file name cannot be empty or only with empty spaces!"
         }
     },
 };

 export default receiveDossierModal;